---
swagger: "2.0"
info:
  description: "Rendez-vous sur http://editor.swagger.io/ pour générer le code serveur.\
    \ Le script d'injection Gatling séquencera écritures et lectures. 10 injecteurs\
    \ simultanés injecterons 10 000 messages chacuns, soit 100 000 messages au total."
  version: "1.0"
  title: "API IoT - Capgemini Development Challenge"
  contact:
    name: "Ludovic Toinel"
    url: "https://www.yammer.com/capgemini.com/#/Threads/show?threadId=682664973"
    email: "ludovic.toinel@capgemini.com"
host: "localhost:8080"
basePath: "/"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /messages:
    post:
      description: "Service d'acquisition de messages provenant d'objets connectés"
      operationId: "messagesPOST"
      parameters:
      - in: "body"
        name: "message"
        description: "Message transmis par l'objet connecté."
        required: false
        schema:
          $ref: "#/definitions/message"
      responses:
        200:
          description: "Réception du message en succés."
      x-swagger-router-controller: "Default"
  /messages/synthesis:
    get:
      description: "Service fournissant une synthèse des données sur les 60 derniè\
        res minutes, minute en cours incluse. L'objet \"synthesis\" retourné doit\
        \ être unique par type de capteur."
      operationId: "messagesSynthesisGET"
      parameters: []
      responses:
        200:
          description: "successful operation."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/synthesis"
      x-swagger-router-controller: "Default"
definitions:
  message:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identifiant unique du message envoyé par le capteur, un controle\
          \ des doublons doit être effectué (max 64 chars)."
      timestamp:
        type: "string"
        format: "date-time"
        description: "Horaire de la fabrication du message par le capteur (format\
          \ RFC3339). Ce timestamp fait fois lors calcul de la synthèse."
      sensorType:
        type: "integer"
        format: "int32"
        description: "Type de capteur à l'origine de l'emission du message."
      value:
        type: "integer"
        format: "int64"
        description: "Valeur transmise par le capteur."
  synthesis:
    type: "object"
    properties:
      sensorType:
        type: "integer"
        format: "int32"
        description: "Type de capteur à l'origine de l'emission du message."
      minValue:
        type: "integer"
        format: "int64"
        description: "Valeur minimum transmise par ce type de capteur."
      maxValue:
        type: "integer"
        format: "int64"
        description: "Valeur maximale transmise par ce capteur type de capteur."
      mediumValue:
        type: "integer"
        format: "int64"
        description: "Valeur moyenne des données transmises par ce type de capteur."
